services:
  mall-admin:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mall-admin
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - /opt/mall/logs/mall-admin:/app/logs
      - /etc/localtime:/etc/localtime:ro
    environment:
      TZ: Asia/Shanghai
    deploy:
      resources:
        limits:
          memory: 450M
    networks:
      - mall-network

  mall-portal:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mall-portal
    restart: always
    ports:
      - "8085:8085"
    volumes:
      - /opt/mall/logs/mall-portal:/app/logs
      - /etc/localtime:/etc/localtime:ro
    environment:
      TZ: Asia/Shanghai
    deploy:
      resources:
        limits:
          memory: 450M
    networks:
      - mall-network

  mall-search:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mall-search
    restart: always
    ports:
      - "8081:8081"
    volumes:
      - /opt/mall/logs/mall-search:/app/logs
      - /etc/localtime:/etc/localtime:ro
    environment:
      TZ: Asia/Shanghai
    deploy:
      resources:
        limits:
          memory: 400M
    networks:
      - mall-network

networks:
  mall-network:
    name: mall-network
    external: true
